import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=process.env.TEST_ORIGIN||'http://127.0.0.1:5173';
if(!['127.0.0.1','localhost'].includes(new URL(base).hostname))throw Error('Flow tests are restricted to a disposable local server.');
const token=fs.readFileSync('.dev.vars','utf8').match(/MASTER_SETUP_TOKEN=(.*)/)[1];
const password='DisposableTest-'+crypto.randomUUID();
async function request(path,p,cookie=''){const res=await fetch(base+'/api/nr/'+path,{method:p===undefined?'GET':'POST',headers:{Origin:base,'Content-Type':'application/json',Cookie:cookie},body:p===undefined?undefined:JSON.stringify(p)});const data=await res.json();return {status:res.status,data,cookie:res.headers.get('set-cookie')?.split(';')[0]||cookie}}
function ok(r){assert.equal(r.status,200,JSON.stringify(r.data));return r}
const anonymous=await request('state');assert.equal(anonymous.status,401);
const setup=ok(await request('auth/setup',{token,name:'Test Stylist',password}));const admin=setup.cookie;
assert.equal((await request('auth/setup',{token,name:'Other',password})).status,409);
const invite1=ok(await request('clients/invite',{name:'Client One',email:'client-one@example.test'},admin));
const invite2=ok(await request('clients/invite',{name:'Client Two',email:'client-two@example.test'},admin));
const accept=async i=>ok(await request('auth/accept',{token:new URL(i.data.invitationUrl).searchParams.get('invite'),name:'Test Client',password}));
const client1=await accept(invite1);const client2=await accept(invite2);const id1=invite1.data.clientId;const id2=invite2.data.clientId;
assert.equal((await request('auth/accept',{token:new URL(invite1.data.invitationUrl).searchParams.get('invite'),name:'Again',password})).status,400);
const session=ok(await request('sessions/save',{clientId:id1,title:'Fall styling',description:'Test session'},admin)).data.id;
assert.equal(ok(await request('state',undefined,client1.cookie)).data.sessions.length,0,'Draft should be private');
const item=ok(await request('items/save',{sessionId:session,name:'Test Jeans',brand:'Mavi',price:138.50,url:'https://www.nordstrom.com/s/6518494?color=444449WGUJ',category:'Jeans',size:'32 × 30',color:'Mid Foggy',image:''},admin)).data.id;
assert.equal((await request('sessions/share',{id:session},client1.cookie)).status,403);
ok(await request('sessions/share',{id:session},admin));
assert.equal(ok(await request('state',undefined,client1.cookie)).data.sessions.length,1);
assert.equal(ok(await request('state',undefined,client2.cookie)).data.sessions.length,0);
assert.equal((await request('items/choice',{id:item,choice:'now'},client2.cookie)).status,403);
assert.equal((await request('profile/save',{id:id1,name:'Intruder',profile:{}},client2.cookie)).status,403);
const address={streetAddress:'123 Main Street',town:'Fairfax',state:'VA',zip:'01234',tops:'Medium'};
ok(await request('profile/save',{id:id1,name:'Test Client',profile:address},admin));
const savedProfile=ok(await request('state',undefined,client1.cookie)).data.user.profile;
for(const [key,value] of Object.entries(address))assert.equal(savedProfile[key],value);
ok(await request('items/choice',{id:item,choice:'later'},client1.cookie));
assert.equal(ok(await request('state',undefined,client1.cookie)).data.items[0].choice,'later');
assert.equal((await request('items/purchase',{id:item,purchased:true},client1.cookie)).status,400);
ok(await request('items/choice',{id:item,choice:'now'},client1.cookie));
assert.equal((await request('items/purchase',{id:item,purchased:true},admin)).status,403);
assert.equal((await request('items/purchase',{id:item,purchased:true},client2.cookie)).status,403);
assert.equal((await request('items/purchase',{id:item,purchased:'yes'},client1.cookie)).status,400);
ok(await request('items/purchase',{id:item,purchased:true},client1.cookie));
let purchasedState=ok(await request('state',undefined,admin)).data;
assert.equal(purchasedState.items[0].purchased,true);assert.ok(purchasedState.items[0].purchasedAt);assert.equal(purchasedState.wardrobe.length,0,'Ordered items must not enter wardrobe before kept confirmation');
const freshLogin=ok(await request('auth/login',{email:'client-one@example.test',password}));assert.equal(ok(await request('state',undefined,freshLogin.cookie)).data.items[0].purchased,true,'Purchase progress must survive a fresh login');
ok(await request('items/purchase',{id:item,purchased:false},client1.cookie));assert.equal(ok(await request('state',undefined,client1.cookie)).data.items[0].purchased,false);
ok(await request('items/purchase',{id:item,purchased:true},client1.cookie));
assert.equal(ok(await request('state',undefined,admin)).data.items[0].choice,'now');assert.equal(ok(await request('state',undefined,admin)).data.items[0].price,138.5);
assert.equal((await request('items/save',{sessionId:session,name:'Missing price',price:'',url:'https://www.jcrew.com/p/CX424'},admin)).status,400);
assert.equal((await request('sessions/complete',{id:session,outcomes:{}},client1.cookie)).status,400);
ok(await request('sessions/complete',{id:session,outcomes:{[item]:'kept'}},client1.cookie));
ok(await request('sessions/complete',{id:session,outcomes:{[item]:'kept'}},client1.cookie));
assert.equal((await request('items/purchase',{id:item,purchased:false},client1.cookie)).status,400);
let state=ok(await request('state',undefined,client1.cookie)).data;assert.equal(state.wardrobe.length,1,'Completion must be idempotent');
assert.equal(state.sessions[0].status,'completed');assert.equal(state.wardrobe[0].origin,'recommendation');
assert.equal((await request('items/save',{id:item,sessionId:session,name:'Change',price:1,url:'https://www.jcrew.com/p/CX424'},admin)).status,400);
ok(await request('wardrobe/save',{clientId:id1,name:'Existing shirt',category:'Tops & Shirts'},admin));
state=ok(await request('state',undefined,client1.cookie)).data;assert.equal(state.wardrobe.length,2);
ok(await request('wardrobe/remove',{id:state.wardrobe[0].id},client1.cookie));
assert.equal(ok(await request('state',undefined,client1.cookie)).data.wardrobe.length,1);
assert.equal((await request('wardrobe/remove',{id:state.wardrobe[1].id},client2.cookie)).status,403);
ok(await request('messages/send',{clientId:id1,body:'How does this fit?'},client1.cookie));
ok(await request('messages/send',{clientId:id1,body:'Try the recommended size.'},admin));
assert.equal(ok(await request('state',undefined,client1.cookie)).data.messages.length,2);
assert.equal(ok(await request('state',undefined,client2.cookie)).data.messages.length,0);
assert.equal((await request('messages/send',{clientId:id1,body:'Intrusion'},client2.cookie)).status,403);
const adminInvite=ok(await request('clients/invite',{name:'Assistant',email:'assistant@example.test',role:'admin'},admin));
const secondary=await accept(adminInvite);
assert.equal(ok(await request('state',undefined,secondary.cookie)).data.clients.length,2);
assert.equal((await request('clients/invite',{name:'Bad',email:'bad@example.test',role:'admin'},secondary.cookie)).status,403);
ok(await request('admins/deactivate',{id:adminInvite.data.clientId},admin));
assert.equal((await request('state',undefined,secondary.cookie)).status,401);
assert.equal((await request('items/import',{url:'https://127.0.0.1/private'},admin)).status,400);
const unsupported=ok(await request('items/import',{url:'https://www.example.com/product'},admin));assert.equal(unsupported.data.complete,false);assert.ok(unsupported.data.warning);
const imported=ok(await request('items/import',{url:'https://www.jcrew.com/p/CX424?color_name=faded-lilac'},admin));if(imported.data.complete){assert.equal(imported.data.item.name,'Cable-knit sweater-polo in vintage wool');assert.equal(imported.data.item.price,148);}else{assert.ok(imported.data.warning,'Blocked retailer must show a recoverable warning');console.log('Retailer runtime fetch requires rendering service; manual fallback verified.');}
const noOrigin=await fetch(base+'/api/nr/messages/send',{method:'POST',headers:{'Content-Type':'application/json',Cookie:admin},body:JSON.stringify({clientId:id1,body:'blocked'})});assert.equal(noOrigin.status,403);
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aNOsAAAAASUVORK5CYII=','base64');
const upload=await fetch(base+'/api/nr/upload?clientId='+id1,{method:'POST',headers:{Origin:base,Cookie:admin,'Content-Type':'image/png'},body:png});assert.equal(upload.status,200);const uploaded=await upload.json();
ok(await request('wardrobe/save',{clientId:id1,name:'Photo item',category:'Other',assetKey:uploaded.assetKey},admin));
const photo=await fetch(base+'/api/nr/photo?key='+encodeURIComponent(uploaded.assetKey),{headers:{Cookie:client1.cookie}});assert.equal(photo.status,200);
const blocked=await fetch(base+'/api/nr/photo?key='+encodeURIComponent(uploaded.assetKey),{headers:{Cookie:client2.cookie}});assert.equal(blocked.status,403);
const queue=ok(await request('email/status',undefined,admin)).data;assert.ok(queue.emails.length>=6);assert.equal(queue.configured,false);assert.ok(queue.emails.every(e=>e.status==='pending'));
console.log('PASS: invitations, login, roles, draft privacy, cross-client isolation, recommendations, completion, wardrobe, messages, product import, CSRF, photo access, and queued email.');
