import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
const compile=s=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {scrapingBeePage}=await import('data:text/javascript;base64,'+Buffer.from(compile(fs.readFileSync('lib/nr/scrapingbee-page.ts','utf8'))).toString('base64'));
assert.equal(await scrapingBeePage('https://www.jcrew.com/p/CX424','test-key',async(endpoint,options)=>{assert.equal(endpoint.searchParams.get('premium_proxy'),'true');assert.equal(endpoint.searchParams.get('country_code'),'us');assert.equal(endpoint.searchParams.get('render_js'),'true');assert.equal(endpoint.searchParams.get('wait'),'3000');assert.equal(endpoint.searchParams.has('api_key'),false);assert.equal(options.headers.Authorization,'Bearer test-key');return new Response('<h1>Product</h1>');}),'<h1>Product</h1>');
await assert.rejects(()=>scrapingBeePage('https://www.nordstrom.com','test-key',async()=>new Response("<h1>We've noticed some unusual activity</h1>")),/security check/);
await assert.rejects(()=>scrapingBeePage('https://www.nordstrom.com','test-key',async()=>new Response('',{status:429})),/request limit/);
const files=['lib/nr/product-fields.ts','lib/nr/scrapingbee-page.ts','lib/nr/importer.ts'];const combined=files.map(p=>fs.readFileSync(p,'utf8').replace(/^import .*;\n/gm,'')).join('\n');
const prefix="const config=k=>k==='SCRAPINGBEE_API_KEY'?'test-key':'configured';const productUrl=s=>new URL(s);const text=(s,max=5000)=>String(s??'').trim().slice(0,max);const fail=()=>{throw Error('invalid URL')};const cloudflarePage=()=>{throw Error('Cloudflare must not run when ScrapingBee is configured')};\n";
const {importProduct}=await import('data:text/javascript;base64,'+Buffer.from(compile(prefix+combined)).toString('base64'));
const originalFetch=globalThis.fetch;let renderedRequests=0;
try{globalThis.fetch=async url=>{if(String(url).startsWith('https://www.nordstrom.com'))return new Response("<h1>We've noticed some unusual activity</h1>");renderedRequests++;return new Response('<script type="application/ld+json">'+JSON.stringify({'@type':'Product',name:'Correct jeans',image:'https://n.nordstrommedia.com/product.jpeg',offers:{price:138,priceCurrency:'USD'}})+'</script>');};const r=await importProduct('https://www.nordstrom.com/s/6518494');assert.equal(r.complete,true);assert.equal(r.item.name,'Correct jeans');assert.equal(r.item.price,138);assert.equal(renderedRequests,1);
assert.equal(r.timings.renderAttempted,true);assert.equal(r.timings.renderSucceeded,true);assert.equal(r.timings.provider,'ScrapingBee premium US');assert.equal(r.timings.directStatus,200);assert.ok(r.timings.requestId);assert.ok(r.timings.recordedAt);for(const key of ['directMs','renderMs','extractMs','totalMs'])assert.ok(Number.isFinite(r.timings[key])&&r.timings[key]>=0);
globalThis.fetch=async url=>String(url).startsWith('https://www.nordstrom.com')?new Response('',{status:403}):new Response('',{status:429});
const failed=await importProduct('https://www.nordstrom.com/s/6518494');assert.equal(failed.complete,false);assert.equal(failed.timings.renderAttempted,true);assert.equal(failed.timings.renderSucceeded,false);assert.equal(failed.timings.directStatus,403);assert.ok(failed.warning);assert.ok(failed.timings.totalMs>=0);
const unsupported=await importProduct('https://example.com/product');assert.equal(unsupported.timings.renderAttempted,false);assert.equal(unsupported.timings.provider,'none');assert.equal(unsupported.timings.directMs,0);}finally{globalThis.fetch=originalFetch;}
console.log('PASS: verified premium configuration, server-only key, blocked-page handling, and ScrapingBee precedence through importer.');
