import {env} from 'cloudflare:workers';
import * as S from '@/lib/nr/server';
import {importProduct} from '@/lib/nr/importer';
export const dynamic='force-dynamic';
async function handler(req:Request){try{S.csrf(req);const path=new URL(req.url).pathname.replace('/api/nr/','');const method=req.method;const get=method==='GET';const p:any=get?{}:await req.json();const ip=req.headers.get('cf-connecting-ip')||'local';
if(path==='auth/status'&&get){const user=await S.current(req);return json({user:user?S.safeAccount(user):null,setupRequired:!(await S.one('SELECT id FROM accounts WHERE role=?','master')),setupEnabled:!!S.config('MASTER_SETUP_TOKEN')})}
if(path==='auth/setup'&&!get){await S.throttle('setup:'+ip,5);if(!S.config('MASTER_SETUP_TOKEN')||await S.hash(String(p.token))!==await S.hash(S.config('MASTER_SETUP_TOKEN')))S.fail(403,'The setup code is invalid.');const id=S.uid();const password=await S.passwordHash(S.validatePassword(p.password));const result=await S.exec("INSERT INTO accounts (id,email,name,role,password,created_at) SELECT ?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM accounts WHERE role='master')",id,S.email(S.config('ADMIN_EMAIL')||'cameron.raithel@gmail.com'),S.text(p.name,120)||'Nicole','master',password,S.now());if(!result.meta.changes)S.fail(409,'The master account has already been created.');return json({ok:true},{'Set-Cookie':await S.signIn(id,req)})}
if(path==='auth/login'&&!get){await S.throttle('login-ip:'+ip,30);const email=S.email(p.email);await S.throttle('login-email:'+email,10);const account=await S.one('SELECT * FROM accounts WHERE email=? AND active=1',email);const stored=account?.password||await S.passwordHash('a-dummy-password-for-timing');const valid=await S.verifyPassword(String(p.password||''),stored);if(!account?.password||!valid)S.fail(401,'The email or password is incorrect.');return json({ok:true},{'Set-Cookie':await S.signIn(account.id,req)})}
if(path==='auth/accept'&&!get){await S.throttle('accept:'+ip,15);const hash=await S.hash(String(p.token));const t=await S.one('SELECT * FROM tokens WHERE hash=? AND kind=? AND expires>?',hash,'invite',Date.now());if(!t)S.fail(400,'This invitation has expired or has already been used.');const account=await S.one('SELECT * FROM accounts WHERE id=? AND active=1',t.account_id);if(!account||account.password)S.fail(400,'This account is not available for activation.');const name=S.text(p.name,120);if(!name)S.fail(400,'Enter your name.');const password=await S.passwordHash(S.validatePassword(p.password));const claimed=await dbBatch([S.db().prepare('DELETE FROM tokens WHERE hash=? AND expires>? RETURNING hash').bind(hash,Date.now()),S.db().prepare('UPDATE accounts SET password=?,name=? WHERE id=? AND password IS NULL AND active=1').bind(password,name,t.account_id)]);if(!claimed[0].results.length||!claimed[1].meta.changes)S.fail(409,'This invitation has already been used.');return json({ok:true},{'Set-Cookie':await S.signIn(t.account_id,req)})}
if(path==='auth/reset-request'&&!get){await S.throttle('reset:'+ip,5);const email=S.email(p.email);const a=await S.one('SELECT * FROM accounts WHERE email=? AND active=1',email);if(a?.password){const token=await S.makeToken(a.id,'reset',{},3600000);await S.queueEmail(email,'Reset your styling account password',`Reset your password within one hour: ${S.link(req,'/?reset='+token)}`);await S.flushEmails()}return json({ok:true,message:'If an active account exists, a reset email will be sent when email delivery is available.'})}
if(path==='auth/reset'&&!get){await S.throttle('reset-confirm:'+ip,10);const hash=await S.hash(String(p.token));const t=await S.one('SELECT * FROM tokens WHERE hash=? AND kind=? AND expires>?',hash,'reset',Date.now());if(!t)S.fail(400,'This reset link has expired or was already used.');const password=await S.passwordHash(S.validatePassword(p.password));const r=await S.exec('DELETE FROM tokens WHERE hash=? AND expires>? RETURNING hash',hash,Date.now());if(!r.results?.length)S.fail(409,'This link has already been used.');await dbBatch([S.db().prepare('UPDATE accounts SET password=? WHERE id=?').bind(password,t.account_id),S.db().prepare('DELETE FROM auth_sessions WHERE account_id=?').bind(t.account_id),S.db().prepare('DELETE FROM tokens WHERE account_id=? AND kind=?').bind(t.account_id,'reset')]);return json({ok:true})}
if(path==='auth/confirm-email'&&!get){const hash=await S.hash(String(p.token));const t=await S.one('SELECT * FROM tokens WHERE hash=? AND kind=? AND expires>?',hash,'email',Date.now());if(!t)S.fail(400,'This verification link has expired or was already used.');const e=JSON.parse(t.payload).email;const used=await S.exec('DELETE FROM tokens WHERE hash=? AND expires>? RETURNING hash',hash,Date.now());if(!used.results?.length)S.fail(409,'This verification link has already been used.');await S.exec('UPDATE accounts SET email=? WHERE id=?',e,t.account_id);await S.exec('DELETE FROM auth_sessions WHERE account_id=?',t.account_id);return json({ok:true})}
const a=await S.requireUser(req);
if(path==='auth/logout'&&!get){const raw=req.headers.get('cookie')?.match(/nr_session=([a-f0-9]{64})/)?.[1];if(raw)await S.exec('DELETE FROM auth_sessions WHERE hash=?',await S.hash(raw));return json({ok:true},{'Set-Cookie':'nr_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0'})}
if(path==='state'&&get){const isAdmin=a.role!=='client';const accounts=isAdmin?await S.rows('SELECT * FROM accounts WHERE role=? AND active=1 ORDER BY name','client'):[];const load=async(table:string)=>{const result=isAdmin?await S.rows(`SELECT * FROM ${table}`):await S.rows(`SELECT * FROM ${table} WHERE client_id=?`,a.id);return result.map(S.unpack)};let sessions=await load('styling_sessions');if(!isAdmin)sessions=sessions.filter(s=>s.status!=='draft'&&!s.archived);const ids=new Set(sessions.map(s=>s.id));const items=(await load('recommendations')).filter(i=>ids.has(i.sessionId));const wardrobe=(await load('wardrobe')).filter(w=>!w.removed);const messages=await load('messages');const notifications=(await S.rows('SELECT * FROM notifications WHERE account_id=?',a.id)).map(r=>({...JSON.parse(r.data),id:r.id}));const admins=a.role==='master'?(await S.rows('SELECT * FROM accounts WHERE role IN (?,?) AND active=1','admin','master')).map(S.safeAccount):[];return json({user:S.safeAccount(a),clients:accounts.map(S.safeAccount),sessions,items,wardrobe,messages,notifications,admins,emailConfigured:!!(S.config('RESEND_API_KEY')&&S.config('EMAIL_FROM'))})}
if(path==='clients/invite'&&!get){S.admin(a);const targetRole=p.role==='admin'?'admin':'client';if(targetRole==='admin')S.master(a);const e=S.email(p.email);let target=await S.one('SELECT * FROM accounts WHERE email=?',e);if(target&&target.role!==targetRole)S.fail(409,'An account with this email already has a different role.');if(target?.password)S.fail(409,'This account is already active.');if(!target){const id=S.uid();await S.exec('INSERT INTO accounts (id,email,name,role,profile,created_at) VALUES (?,?,?,?,?,?)',id,e,S.text(p.name,120)||e,targetRole,'{}',S.now());target={id}}else if(!target.active)S.fail(409,'This account has been deactivated.');await S.exec('DELETE FROM tokens WHERE account_id=? AND kind=?',target.id,'invite');const token=await S.makeToken(target.id,'invite');const url=S.link(req,'/?invite='+token);await S.queueEmail(e,'Your invitation to Nicole Raithel Styles',`Your styling space is ready. Create your account using this invitation within 48 hours:\n\n${url}\n\nNicole Raithel Styles`);const delivery=await S.flushEmails();return json({ok:true,invitationUrl:url,emailConfigured:delivery.configured,clientId:target.id})}
if(path==='admins/deactivate'&&!get){S.master(a);if(p.id===a.id)S.fail(400,'You cannot deactivate your own master account.');const target=await S.one('SELECT * FROM accounts WHERE id=? AND role=?',p.id,'admin');if(!target)S.fail(404,'Administrator not found.');await dbBatch([S.db().prepare('UPDATE accounts SET active=0 WHERE id=?').bind(p.id),S.db().prepare('DELETE FROM auth_sessions WHERE account_id=?').bind(p.id),S.db().prepare('DELETE FROM tokens WHERE account_id=?').bind(p.id)]);return json({ok:true})}
if(path==='profile/save'&&!get){const id=String(p.id||a.id);if(id!==a.id)await S.clientAccess(a,id);const name=S.text(p.name,120);if(!name)S.fail(400,'Enter a name.');const fields=['age','phone','address','tops','pants','jeans','shoes','dress','inseam','height','fit','notes'];const profile=Object.fromEntries(fields.map(k=>[k,S.text(p.profile?.[k],k==='notes'?3000:500)]));await S.exec('UPDATE accounts SET name=?,profile=? WHERE id=?',name,JSON.stringify(profile),id);if(id!==a.id&&p.email){const newEmail=S.email(p.email);const target=await S.one('SELECT email FROM accounts WHERE id=?',id);if(newEmail!==target.email){if(await S.one('SELECT id FROM accounts WHERE email=?',newEmail))S.fail(409,'That email is already in use.');const token=await S.makeToken(id,'email',{email:newEmail});await S.queueEmail(newEmail,'Verify your updated styling account email',`Your stylist requested an email update. Confirm it here: ${S.link(req,'/?verify='+token)}`);await S.queueEmail(target.email,'Email change requested','Your stylist requested an update to your account email. Contact your stylist if this is unexpected.');await S.flushEmails();return json({ok:true,emailVerificationPending:true})}}return json({ok:true})}
if(path==='account/email'&&!get){if(!await S.verifyPassword(String(p.password||''),a.password||''))S.fail(403,'Confirm your current password.');const e=S.email(p.email);if(e===a.email)S.fail(400,'That is already your email address.');if(await S.one('SELECT id FROM accounts WHERE email=?',e))S.fail(409,'That email is already in use.');const token=await S.makeToken(a.id,'email',{email:e});await S.queueEmail(e,'Verify your new styling account email',`Confirm your new email address: ${S.link(req,'/?verify='+token)}`);await S.queueEmail(a.email,'Email change requested','A change to your account email was requested. Contact your stylist if you did not request this.');const delivery=await S.flushEmails();return json({ok:true,emailConfigured:delivery.configured,message:'Verification is required before your account email changes.'})}
if(path==='account/password'&&!get){if(!await S.verifyPassword(String(p.currentPassword||''),a.password||''))S.fail(403,'Your current password is incorrect.');await S.exec('UPDATE accounts SET password=? WHERE id=?',await S.passwordHash(S.validatePassword(p.password)),a.id);await S.exec('DELETE FROM auth_sessions WHERE account_id=?',a.id);return json({ok:true},{'Set-Cookie':await S.signIn(a.id,req)})}
if(path==='sessions/save'&&!get){S.admin(a);await S.clientAccess(a,String(p.clientId));const title=S.text(p.title,180);if(!title)S.fail(400,'Enter a session title.');if(p.id){const old=await S.sessionAccess(a,p.id);if(old.client_id!==p.clientId)S.fail(400,'A session cannot be moved to another client.');const d=JSON.parse(old.data);await S.exec('UPDATE styling_sessions SET data=? WHERE id=?',JSON.stringify({...d,title,description:S.text(p.description),updatedAt:S.now()}),p.id);return json({ok:true,id:p.id})}const id=S.uid();await S.exec('INSERT INTO styling_sessions (id,client_id,data) VALUES (?,?,?)',id,p.clientId,JSON.stringify({title,description:S.text(p.description),status:'draft',createdAt:S.now(),updatedAt:S.now()}));return json({ok:true,id})}
if(path==='sessions/share'&&!get){S.admin(a);const s=await S.sessionAccess(a,p.id);const d=JSON.parse(s.data);if(d.archived)S.fail(400,'Restore this session before sharing it.');if(d.status==='completed')S.fail(400,'Reopen the session before sharing updates.');const count=await S.one('SELECT COUNT(*) n FROM recommendations WHERE session_id=? AND json_extract(data,?) IS NOT 1',p.id,'$.removed');if(!count.n)S.fail(400,'Add at least one recommendation before sharing.');await S.exec('UPDATE styling_sessions SET data=? WHERE id=?',JSON.stringify({...d,status:'shared',sharedAt:S.now(),updatedAt:S.now()}),p.id);await S.notify(s.client_id,d.status==='draft'?'New styling recommendations':'Your recommendations have been updated',`Your session “${d.title}” is ready to review.`,req,p.id);const delivery=await S.flushEmails();return json({ok:true,emailConfigured:delivery.configured})}
if(path==='sessions/archive'&&!get){S.admin(a);const s=await S.sessionAccess(a,p.id);await S.exec('UPDATE styling_sessions SET data=? WHERE id=?',JSON.stringify({...JSON.parse(s.data),archived:!JSON.parse(s.data).archived}),p.id);return json({ok:true})}
if(path==='sessions/reopen'&&!get){S.admin(a);const s=await S.sessionAccess(a,p.id);await S.exec('UPDATE styling_sessions SET data=? WHERE id=?',JSON.stringify({...JSON.parse(s.data),status:'shared',completedAt:null}),p.id);return json({ok:true})}
if(path==='items/import'&&!get){S.admin(a);await S.throttle('import:'+a.id,50);return json(await importProduct(p.url))}
if(path==='items/save'&&!get){S.admin(a);const session=await S.sessionAccess(a,p.sessionId);if(JSON.parse(session.data).status==='completed')S.fail(400,'Reopen the session before editing recommendations.');const fields=S.itemFields(p);if(p.id){const old=await S.one('SELECT * FROM recommendations WHERE id=? AND session_id=?',p.id,p.sessionId);if(!old)S.fail(404,'Recommendation not found.');await S.exec('UPDATE recommendations SET data=? WHERE id=?',JSON.stringify({...JSON.parse(old.data),...fields,updatedAt:S.now()}),p.id);return json({ok:true})}const id=S.uid();await S.exec('INSERT INTO recommendations (id,session_id,client_id,data) VALUES (?,?,?,?)',id,p.sessionId,session.client_id,JSON.stringify({...fields,choice:'undecided',outcome:'pending',createdAt:S.now()}));return json({ok:true,id})}
if(path==='items/remove'&&!get){S.admin(a);const item=await S.one('SELECT * FROM recommendations WHERE id=?',p.id);if(!item)S.fail(404,'Recommendation not found.');const session=await S.sessionAccess(a,item.session_id);if(JSON.parse(session.data).status==='completed')S.fail(400,'Reopen the session before editing recommendations.');await S.exec('UPDATE recommendations SET data=? WHERE id=?',JSON.stringify({...JSON.parse(item.data),removed:true,removedAt:S.now()}),p.id);return json({ok:true})}
if(path==='items/choice'&&!get){if(a.role!=='client')S.fail(403,'Purchase choices are set by the client.');if(!['now','later','pass','undecided'].includes(p.choice))S.fail(400,'Choose a valid purchase option.');const item=await S.one('SELECT * FROM recommendations WHERE id=?',p.id);if(!item)S.fail(404,'Recommendation not found.');const s=await S.sessionAccess(a,item.session_id);if(JSON.parse(s.data).status==='completed'||JSON.parse(s.data).archived||JSON.parse(item.data).removed)S.fail(400,'This recommendation is closed.');await S.exec('UPDATE recommendations SET data=? WHERE id=?',JSON.stringify({...JSON.parse(item.data),choice:p.choice,updatedAt:S.now()}),p.id);return json({ok:true})}
if(path==='sessions/complete'&&!get){if(a.role!=='client')S.fail(403,'Only the client can confirm purchases.');const s=await S.sessionAccess(a,p.id);const d=JSON.parse(s.data);if(d.archived)S.fail(400,'This session is archived.');if(d.status==='completed')return json({ok:true});const items=(await S.rows('SELECT * FROM recommendations WHERE session_id=?',p.id)).map(S.unpack).filter(i=>!i.removed);const commands:D1PreparedStatement[]=[];for(const item of items){const outcome=p.outcomes?.[item.id];if(!['kept','returned','not-purchased'].includes(outcome))S.fail(400,'Confirm an outcome for every recommendation before completing the session.');commands.push(S.db().prepare('UPDATE recommendations SET data=? WHERE id=?').bind(JSON.stringify({...item,outcome,confirmedAt:S.now()}),item.id));if(outcome==='kept')commands.push(S.db().prepare('INSERT INTO wardrobe (id,client_id,recommendation_id,data) VALUES (?,?,?,?) ON CONFLICT(recommendation_id) DO NOTHING').bind(S.uid(),a.id,item.id,JSON.stringify({...item,origin:'recommendation',recommendationId:item.id,addedAt:S.now(),removed:false})));}commands.push(S.db().prepare('UPDATE styling_sessions SET data=? WHERE id=?').bind(JSON.stringify({...d,status:'completed',completedAt:S.now()}),p.id));await dbBatch(commands);return json({ok:true})}
if(path==='wardrobe/save'&&!get){const id=String(p.clientId||a.id);await S.clientAccess(a,id);const name=S.text(p.name,250);if(!name)S.fail(400,'Enter an item name.');const fields={name,category:S.text(p.category,100)||'Other',size:S.text(p.size,100),color:S.text(p.color,150),brand:S.text(p.brand,150),notes:S.text(p.notes),image:p.image?S.imageUrl(p.image):'',assetKey:S.text(p.assetKey,180)};if(fields.assetKey){if(!fields.assetKey.startsWith(id+'/'))S.fail(403,'This photo belongs to another account.');if(!env.BUCKET||!await env.BUCKET.head(fields.assetKey))S.fail(400,'Upload the photo before saving.');}if(p.id){const old=await S.one('SELECT * FROM wardrobe WHERE id=? AND client_id=?',p.id,id);if(!old)S.fail(404,'Wardrobe item not found.');await S.exec('UPDATE wardrobe SET data=? WHERE id=?',JSON.stringify({...JSON.parse(old.data),...fields}),p.id)}else await S.exec('INSERT INTO wardrobe (id,client_id,data) VALUES (?,?,?)',S.uid(),id,JSON.stringify({...fields,origin:'owned',addedAt:S.now()}));return json({ok:true})}
if(path==='wardrobe/remove'&&!get){const item=await S.one('SELECT * FROM wardrobe WHERE id=?',p.id);if(!item)S.fail(404,'Wardrobe item not found.');await S.clientAccess(a,item.client_id);await S.exec('UPDATE wardrobe SET data=? WHERE id=?',JSON.stringify({...JSON.parse(item.data),removed:true,removedAt:S.now()}),p.id);return json({ok:true})}
if(path==='messages/send'&&!get){const clientId=String(p.clientId||a.id);const c=await S.clientAccess(a,clientId);const body=S.text(p.body);if(!body)S.fail(400,'Write a message before sending.');await S.exec('INSERT INTO messages (id,client_id,sender_id,data) VALUES (?,?,?,?)',S.uid(),clientId,a.id,JSON.stringify({body,senderName:a.name,createdAt:S.now(),read:false}));if(a.role==='client'){for(const recipient of await S.rows('SELECT id,email FROM accounts WHERE role IN (?,?) AND active=1','master','admin')){await S.exec('INSERT INTO notifications (id,account_id,data) VALUES (?,?,?)',S.uid(),recipient.id,JSON.stringify({title:`New message from ${c.name}`,body,clientId,read:false,createdAt:S.now()}));await S.queueEmail(recipient.email,`New message from ${c.name}`,`A client message is waiting in your styling space: ${S.link(req,'/')}`)}}else await S.notify(clientId,`New message from ${a.name}`,'A new message is waiting in your styling space.',req);await S.flushEmails();return json({ok:true})}
if(path==='messages/read'&&!get){const id=String(p.clientId||a.id);await S.clientAccess(a,id);const messages=await S.rows('SELECT * FROM messages WHERE client_id=? AND sender_id<>?',id,a.id);await dbBatch(messages.map(m=>S.db().prepare('UPDATE messages SET data=? WHERE id=?').bind(JSON.stringify({...JSON.parse(m.data),read:true}),m.id)));return json({ok:true})}
if(path==='notifications/read'&&!get){const records=await S.rows('SELECT * FROM notifications WHERE account_id=?',a.id);await dbBatch(records.map(r=>S.db().prepare('UPDATE notifications SET data=? WHERE id=?').bind(JSON.stringify({...JSON.parse(r.data),read:true}),r.id)));return json({ok:true})}
if(path==='email/status'&&get){S.admin(a);return json({configured:!!(S.config('RESEND_API_KEY')&&S.config('EMAIL_FROM')),emails:await S.rows('SELECT id,recipient,subject,status,attempts,error,created_at FROM outbox ORDER BY created_at DESC LIMIT 100')})}
if(path==='email/retry'&&!get){S.admin(a);return json(await S.flushEmails())}
S.fail(404,'This action is not available.');
}catch(err){if(err instanceof S.HttpError)return json({error:err.message},{},err.status);console.error('NR Styles request failed',err instanceof Error?err.message:'Unknown error');const m=err instanceof Error?err.message:'';if(m.includes('UNIQUE constraint'))return json({error:'This record already exists. Please reload and try again.'},{},409);return json({error:'We could not complete this action. Your input has been preserved; please try again.'},{},500)}}
function json(data:any,headers:Record<string,string>={},status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}})}
async function dbBatch(statements:D1PreparedStatement[]){return statements.length?S.db().batch(statements):[]}
export const GET=handler;export const POST=handler;
