import {env} from 'cloudflare:workers';
import {categories} from './types';
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export const fail=(status:number,message:string):never=>{throw new HttpError(status,message)};
export const db=()=>env.DB??fail(503,'Storage is unavailable. Please try again shortly.');
export const config=(key:string)=>String((env as any)[key]||process.env[key]||'');
export const uid=()=>crypto.randomUUID();
export const now=()=>new Date().toISOString();
export const safeAccount=(a:any)=>({id:a.id,email:a.email,name:a.name,role:a.role,profile:JSON.parse(a.profile||'{}'),active:a.active,hasPassword:!!a.password});
export async function one(sql:string,...args:any[]){return db().prepare(sql).bind(...args).first<any>()}
export async function rows(sql:string,...args:any[]){return (await db().prepare(sql).bind(...args).all<any>()).results}
export async function exec(sql:string,...args:any[]){return db().prepare(sql).bind(...args).run()}
export const unpack=(r:any)=>({...JSON.parse(r.data),id:r.id,clientId:r.client_id,...(r.session_id?{sessionId:r.session_id}:{}),...(r.sender_id?{senderId:r.sender_id}:{})});
export async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(n=>n.toString(16).padStart(2,'0')).join('')}
export function random(){return Array.from(crypto.getRandomValues(new Uint8Array(32))).map(n=>n.toString(16).padStart(2,'0')).join('')}
export async function passwordHash(password:string,salt=random()){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const result=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},k,256);return `${salt}:${Array.from(new Uint8Array(result)).map(n=>n.toString(16).padStart(2,'0')).join('')}`}
export async function verifyPassword(password:string,stored:string){const computed=await passwordHash(password,stored.split(':')[0]);let different=stored.length^computed.length;for(let i=0;i<stored.length;i++)different|=stored.charCodeAt(i)^(computed.charCodeAt(i)||0);return different===0}
export function validatePassword(s:any){if(typeof s!=='string'||s.length<12||s.length>256)fail(400,'Use a password between 12 and 256 characters.');return s}
export function email(s:any){const v=String(s||'').trim().toLowerCase();if(v.length>254||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))fail(400,'Enter a valid email address.');return v}
export function text(s:any,max=5000){return String(s??'').trim().slice(0,max)}
export function csrf(req:Request){if(!['GET','HEAD'].includes(req.method)){const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)fail(403,'Please reload the page before trying again.')}}
export async function throttle(key:string,limit=10){const time=Date.now();const r=await db().prepare('INSERT INTO rate_limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires < ? THEN 1 ELSE count+1 END, expires=CASE WHEN expires < ? THEN ? ELSE expires END RETURNING count').bind(key,time+15*60*1000,time,time,time+15*60*1000).first<any>();if(r.count>limit)fail(429,'Too many attempts. Please wait 15 minutes.');}
export async function current(req:Request){const token=req.headers.get('cookie')?.match(/(?:^|;\s*)nr_session=([a-f0-9]{64})/)?.[1];if(!token)return null;return one('SELECT a.* FROM auth_sessions s JOIN accounts a ON a.id=s.account_id WHERE s.hash=? AND s.expires>? AND a.active=1',await hash(token),Date.now())}
export async function requireUser(req:Request){return await current(req)??fail(401,'Please sign in to continue.')}
export function admin(a:any){if(!['admin','master'].includes(a.role))fail(403,'Administrator access is required.')}
export function master(a:any){if(a.role!=='master')fail(403,'Only the master administrator can do this.')}
export async function clientAccess(a:any,id:string){if(a.role==='client'&&a.id!==id)fail(403,'This account is not available.');const c=await one('SELECT * FROM accounts WHERE id=? AND role=?',id,'client');if(!c)fail(404,'Client not found.');return c}
export async function sessionAccess(a:any,id:string){const s=await one('SELECT * FROM styling_sessions WHERE id=?',id);if(!s)fail(404,'Session not found.');await clientAccess(a,s.client_id);if(a.role==='client'&&JSON.parse(s.data).status==='draft')fail(404,'Session not found.');return s}
export async function signIn(id:string,req:Request){const token=random();await exec('INSERT INTO auth_sessions (hash,account_id,expires) VALUES (?,?,?)',await hash(token),id,Date.now()+7*86400000);return `nr_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800${new URL(req.url).protocol==='https:'?'; Secure':''}`}
export function link(req:Request,path:string){const origin=config('APP_ORIGIN')||new URL(req.url).origin;return new URL(path,origin).toString()}
export async function makeToken(accountId:string,kind:string,payload:any={},duration=48*3600000){const token=random();await exec('INSERT INTO tokens (hash,account_id,kind,expires,payload) VALUES (?,?,?,?,?)',await hash(token),accountId,kind,Date.now()+duration,JSON.stringify(payload));return token}
export async function queueEmail(recipient:string,subject:string,body:string){const id=uid();await exec('INSERT INTO outbox (id,recipient,subject,body,created_at) VALUES (?,?,?,?,?)',id,recipient,subject,body,now());return id}
export async function flushEmails(){if(!config('RESEND_API_KEY')||!config('EMAIL_FROM'))return {configured:false,sent:0};const pending=await rows('SELECT * FROM outbox WHERE status=? ORDER BY created_at LIMIT 15','pending');let sent=0;for(const e of pending){try{const res=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${config('RESEND_API_KEY')}`,'Content-Type':'application/json','Idempotency-Key':e.id},signal:AbortSignal.timeout(10000),body:JSON.stringify({from:config('EMAIL_FROM'),to:[e.recipient],subject:e.subject,text:e.body})});if(!res.ok)throw Error(`Email provider returned ${res.status}`);await exec('UPDATE outbox SET status=?,attempts=attempts+1,error=NULL WHERE id=?','sent',e.id);sent++}catch(err){await exec('UPDATE outbox SET attempts=attempts+1,error=? WHERE id=?',text((err as Error).message,300),e.id)}}return {configured:true,sent}}
export async function notify(clientId:string,title:string,body:string,req:Request,sessionId?:string){const id=uid();await exec('INSERT INTO notifications (id,account_id,data) VALUES (?,?,?)',id,clientId,JSON.stringify({title,body,sessionId,read:false,createdAt:now()}));const c=await one('SELECT email FROM accounts WHERE id=?',clientId);if(c)await queueEmail(c.email,title,`${body}\n\nOpen your styling space: ${link(req,'/')}\n\nNicole Raithel Styles`)}
export function itemFields(p:any){if(p.price==null||String(p.price).trim()==='')fail(400,'Enter the product price.');const price=Number(p.price);if(!Number.isFinite(price)||price<0||price>1000000)fail(400,'Enter a valid product price.');const url=productUrl(p.url);if(!text(p.name,250))fail(400,'A product name is required.');const currency=text(p.currency||'USD',3).toUpperCase();if(currency!=='USD')fail(400,'The first version supports prices in USD.');return {name:text(p.name,250),brand:text(p.brand,150),price,currency,url:url.toString(),image:imageUrl(p.image),size:text(p.size,100),color:text(p.color,150),category:categories.includes(p.category)?p.category:'Other',notes:text(p.notes)}}
export function productUrl(s:any){let u:URL;try{u=new URL(String(s))}catch{fail(400,'Enter a valid retailer URL.')}if(u!.protocol!=='https:'||u!.username||u!.password)fail(400,'Use an HTTPS retailer link.');return u!}
export function imageUrl(s:any){if(!s)return '';const u=productUrl(s);return u.toString()}
